<a href="https://colab.research.google.com/github/liaalcantara01/CDA-UTEC/blob/main/Lia_Lab3_1_1_SENAMHI_Format_SENAMHI_share.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ejercicio: Datos climáticos estación

Link de datos: https://drive.google.com/drive/folders/1QD_GVY_KDRu6CEtN3qUmybuatw0WjRYx?usp=sharing


Crea un nuevo DataFrame con datos de 1 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Considerar lo siguiente a partir de "tutorial-para-la-descarga-de-datos.pdf".

Los datos de las columnas corresponden a:
- Columna A: Año
- Columna B: Mes
- Columna C: Día
- Columna D: Precipitación acumulada
- Columna E: Temperatura máxima
- Columna F: Temperatura mínima

En las celdas donde aparece -99.9 significa que no hay información disponible para esa variable

Luego:
1. Parsear el nombres de la estación Chosica y leer el archivo.
1. Calcula el promedio mensual de precipitación
1. Calcula el promedio anual de precipitación
2. Identifica el día más lluvioso
4. Exporta los resultados formateados en CSV

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
# Ejercicio: Estación

# Leer los datos de las estaciones y crear un DataFrame combinado
import os

ruta = '/content/drive/MyDrive/Senamhi'

files = os.listdir(ruta)

files

['qc00000543_ñaña.txt',
 'qc00151209_chosica.txt',
 'qc00155213_santa_eulalia.txt',
 'qc00151205_CANCHACALLA.txt',
 'tutorial-para-la-descarga-de-datos.pdf',
 'qc00155224_santiago_de_tuna.txt']

In [26]:
# Parsear el nombre del archivo para obtener el código y nombre de la estación

station = 'qc00151209_chosica.txt'

codigo = station.split('_')[0].replace('qc', '')
nombre = station.split('_')[1].replace('.txt', '')

print(f"Código: {codigo}, Nombre: {nombre}")

Código: 00151209, Nombre: chosica

In [7]:
# Leer el archivo CSV de la estación seleccionada
import pandas as pd

station_df = pd.read_table(
    f'{ruta}/{station}',
    header=None,
    sep=r'\s+',
    na_values=['-999', '-99.9', '-3256']
)

station_df.columns = ['Año', 'Mes', 'Dia', 'Pr', 'Tmax', 'Tmin']  # Asignar nombres de columnas

# Formatear las columnas
station_df['Año'] = station_df['Año'].astype(int)
station_df['Mes'] = station_df['Mes'].astype(int)
station_df['Dia'] = station_df['Dia'].astype(int)

station_df

       Año  Mes  Dia   Pr  Tmax  Tmin
0     1989   12    1  0.0   NaN   NaN
1     1989   12    2  0.0   NaN   NaN
2     1989   12    3  0.0   NaN   NaN
3     1989   12    4  0.0   NaN   NaN
4     1989   12    5  0.0   NaN   NaN
...    ...  ...  ...  ...   ...   ...
8823  2014    1   27  0.0   NaN   NaN
8824  2014    1   28  0.0   NaN   NaN
8825  2014    1   29  0.0   NaN   NaN
8826  2014    1   30  0.0   NaN   NaN
8827  2014    1   31  0.0   NaN   NaN

[8828 rows x 6 columns]

In [12]:
# Precipitacion mensual
precipitacion_mensual = station_df.groupby(['Año', 'Mes'])['Pr'].mean()

# Precipitacion anual
precipitacion_anual = station_df.groupby('Año')['Pr'].mean()

# Dia mas lluvioso
dia_mas_lluvioso = station_df.loc[station_df['Pr'].idxmax()]


print(f"Precipitación mensual:\n{precipitacion_mensual}\n")
print(f"Precipitación anual:\n{precipitacion_anual}\n")
print(f"El día más lluvioso fue el {dia_mas_lluvioso['Año']:.0f}-{dia_mas_lluvioso['Mes']:.0f}-{dia_mas_lluvioso['Dia']:.0f} con {dia_mas_lluvioso['Pr']} mm de precipitación.")

Precipitación mensual:
Año   Mes
1989  12     0.000000
1990  1      0.148387
      2      0.000000
      3      0.151613
      4      0.000000
               ...
2013  9      0.000000
      10     0.000000
      11     0.000000
      12     0.035484
2014  1      0.187097
Name: Pr, Length: 290, dtype: float64

Precipitación anual:
Año
1989    0.000000
1990    0.040548
1991    0.038356
1992    0.022552
1993    0.040000
1994    0.120548
1995    0.053699
1996    0.089617
1997    0.025000
1998    0.054790
1999    0.108493
2000    0.090164
2001    0.070411
2002    0.095890
2003    0.058904
2004    0.015027
2005    0.016164
2006    0.080274
2007    0.043014
2008    0.057104
2009    0.154925
2010    0.003014
2011    0.065205
2012    0.192836
2013    0.019452
2014    0.187097
Name: Pr, dtype: float64

El día más lluvioso fue el 2012-4-4 con 37.0 mm de precipitación.

In [ ]:
# Exportar los resultados

import os

ruta_resultados = '/content/drive/MyDrive/Resultados_SENAMHI'

# Creo una carpeta para gusradar los resultados
os.makedirs(ruta_resultados, exist_ok=True)

precipitacion_mensual.to_csv(
    f'{ruta_resultados}/precipitacion_mensual_chosica.csv'
)

precipitacion_anual.to_csv(
    f'{ruta_resultados}/precipitacion_anual_chosica.csv'
)

dia_mas_lluvioso.to_frame().T.to_csv(
    f'{ruta_resultados}/dia_mas_lluvioso_chosica.csv',
    index=False
)

print("Resultados exportados correctamente.")

### Ejercicio 2: Datos climáticos multiestación

Crea un nuevo DataFrame con datos de 5 estaciones SENAMHI de diferentes regiones del Perú (https://www.senamhi.gob.pe/site/descarga-datos/).

Luego:
1. Paresear el nombres de la estaciones y leer los archivo.
1. Unir las db (Fecha, Est1, Est2, ...)
1. Calcula el promedio mensual de precipitación por región
2. Identifica el mes más lluvioso en cada estación
4. Exporta el resultado formateado a CSV

In [23]:
# Primero leer y unir las 5 estaciones

import pandas as pd
import os

archivos = [archivo for archivo in os.listdir(ruta) if archivo.endswith('.txt')]

estaciones = []

for archivo in archivos:

    # Nombre de la estación:
    nombre = archivo.replace('.txt', '').split('_', 1)[1]

    # Leer los datos:
    df = pd.read_table(
        f'{ruta}/{archivo}',
        header=None,
        sep=r'\s+',
        na_values=['-999', '-99.9', '-3256']
    )

    df.columns = ['Año', 'Mes', 'Dia', 'Pr', 'Tmax', 'Tmin']

    # Crear fecha:
    df['Fecha'] = pd.to_datetime(
        dict(year=df['Año'], month=df['Mes'], day=df['Dia'])
    )

    # Guardamos solo fecha y precipitación:
    estaciones.append(
        df[['Fecha', 'Pr']].rename(columns={'Pr': nombre}).set_index('Fecha')
    )

# Unimos todas las estaciones:
multiestacion_df = pd.concat(estaciones, axis=1).reset_index()

multiestacion_df

,Fecha,ñaña,chosica,santa_eulalia,CANCHACALLA,santiago_de_tuna
0,1963-12-01,NaN,NaN,0.0,NaN,NaN
1,1963-12-02,NaN,NaN,0.0,NaN,NaN
2,1963-12-03,NaN,NaN,0.0,NaN,NaN
3,1963-12-04,NaN,NaN,0.0,NaN,NaN
4,1963-12-05,NaN,NaN,0.2,NaN,NaN
...,...,...,...,...,...,...
18320,2014-01-27,0.0,0.0,0.0,0.0,0.0
18321,2014-01-28,0.0,0.0,0.0,0.2,0.0
18322,2014-01-29,0.0,0.0,0.0,0.0,0.0
18323,2014-01-30,0.0,0.0,0.0,4.5,4.2
18324,2014-01-31,0.0,0.0,0.0,0.0,1.7

In [24]:
# Promedio mensual de precipitación

precipitacion_mensual_estaciones = (
    multiestacion_df
    .set_index('Fecha')
    .resample('ME')
    .mean()
)

# Mes más lluvioso de cada estación

resultado_mes_lluvioso = pd.DataFrame({
    'Mes_mas_lluvioso': precipitacion_mensual_estaciones.idxmax(),
    'Precipitacion_promedio_mm': precipitacion_mensual_estaciones.max()
})

# Para la fecha mostramos solo año y mes
resultado_mes_lluvioso['Mes_mas_lluvioso'] = (
    resultado_mes_lluvioso['Mes_mas_lluvioso'].dt.strftime('%Y-%m')
)

print("PROMEDIO MENSUAL:")
display(precipitacion_mensual_estaciones)

print("\nMES MÁS LLUVIOSO POR ESTACIÓN:")
display(resultado_mes_lluvioso)

PROMEDIO MENSUAL:

              ñaña   chosica  santa_eulalia  CANCHACALLA  santiago_de_tuna
Fecha
1963-12-31       NaN       NaN       0.016129          NaN               NaN
1964-01-31       NaN       NaN       0.061290          NaN          0.225806
1964-02-29  0.000000       NaN       0.341379          NaN          2.046154
1964-03-31  0.000000       NaN       0.309677          NaN          0.532258
1964-04-30  0.000000       NaN       0.203333          NaN          0.800000
...              ...       ...            ...          ...               ...
2013-09-30  0.000000  0.000000       0.000000     0.000000          0.000000
2013-10-31  0.000000  0.000000       0.000000     0.306452          0.000000
2013-11-30  0.000000  0.000000       0.000000     0.373333          0.136667
2013-12-31  0.000000  0.035484       0.293548     1.716129          0.048387
2014-01-31  0.225806  0.187097       0.232258     1.712903          1.283871

[602 rows x 5 columns]

MES MÁS LLUVIOSO POR ESTACIÓN:

                 Mes_mas_lluvioso  Precipitacion_promedio_mm
ñaña                    2002-02                   0.500000
chosica                   2012-04                   1.246667
santa_eulalia             1972-03                   3.551613
CANCHACALLA               1999-02                  12.185714
santiago_de_tuna          1967-02                  11.442857

In [27]:
# Exportar los resultados del Ejercicio 2 en la misma carpeta que se creo para el ejercicio 1

multiestacion_df.to_csv(
    f'{ruta_resultados}/datos_multiestacion.csv',
    index=False,
    sep=';',
    encoding='utf-8-sig'
)

precipitacion_mensual_estaciones.to_csv(
    f'{ruta_resultados}/precipitacion_mensual_estaciones.csv',
    sep=';',
    encoding='utf-8-sig'
)

resultado_mes_lluvioso.to_csv(
    f'{ruta_resultados}/mes_mas_lluvioso_estaciones.csv',
    sep=';',
    encoding='utf-8-sig'
)

print("Resultados del Ejercicio 2 exportados correctamente")

Resultados del Ejercicio 2 exportados correctamente